### ISSUE TITLE
Html highlighting and tag autocompletion

### ISSUE THREAD

**Issue by klis87** [attilabuti/vscode-mjml#14]
Is it possible to have html support in mjml file? Like html tags highlighting or creating `<div></div>` by having just `div` written and pressing `tab` like in `html` files? I tried  
```
"files.associations": {
  "*.mjml": "html"
}
```
but then this plugin doesn't work anymore.

**Comment by klis87** [comment]
I solved it myself:
```
 "emmet.includeLanguages": {
    "mjml": "html"
 }
```
plus installing of `mjml-syntax` plugin

**Comment by alexsasharegan** [comment]
I was having trouble getting this working, but found that it's also import to have this setting set accordingly:

```js
{
  // Shows expanded Emmet abbreviations as suggestions.
  // The option "inMarkupAndStylesheetFilesOnly" applies to html, haml, jade, slim, xml, xsl, css, scss, sass, less and stylus.
  // The option "always" applies to all parts of the file regardless of markup/css.
  "emmet.showExpandedAbbreviation": "always",
}
```
