### ISSUE TITLE
Old previews are cached and new ones does not show

### ISSUE THREAD

**Issue by ddeath** [attilabuti/vscode-mjml#15]
mjml extension: 0.0.9
vscode:
Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:57:00.652Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

OS: Linux

When I open a.mjml and preview it, everything is ok, then I open file b.mjml and when I preview it, the extension still shows a.mjml content

**Comment by attilabuti** [comment]
I have tested this on Ubuntu, and it worked well.
Can you send me a gif of this error?

**Comment by ddeath** [comment]
Sure.

![anim](https://user-images.githubusercontent.com/2537379/32211571-68e26bd4-be13-11e7-9152-383aabfa9b6c.gif)

So steps  to reproduce in my case are:

* open vscode
* open a.mjml
* open preview of a.mjml (works)
* close preview of a.mjml
* open preview of b.mjml (works)
* close preview of b.mjml
* open preview of a.mjml (do not works - this is opening preview of b.mjml)

**Comment by attilabuti** [comment]
Thank you for the feedback. I will fix it in next release.

**Comment by attilabuti** [comment]
Released in v0.1.0
