### ISSUE TITLE
mj-include fails both linting and preview

### ISSUE THREAD

**Issue by c-eliasson** [attilabuti/vscode-mjml#16]
When using a `<mj-include path="templates/shared/header.mjml" />` tag, I get a linting warning.

![screenshot](https://user-images.githubusercontent.com/1837520/33736884-99c5e8b8-db94-11e7-86e3-97df8b3657a0.png)

The preview also fail to show the included content, without errors or warnings.

When running the template through the CLI (and through the `mjml2html` JS module), the output is generated as expected and without warnings.

I'm using version 0.0.9 of the extension, and version 1.18.1 of VS Code on Windows.

**Comment by attilabuti** [comment]
Hello @c-eliasson

Linting warning:
"Sorry for that, but mjml --validate doesn't support mj-include." [#651](https://github.com/mjmlio/mjml/issues/651)

Include:
Replace `<mj-include path="templates/shared/header.mjml" />` to `<mj-include path="../../templates/shared/header.mjml" />` or `<mj-include path="../shared/header.mjml" />` and the preview works as expected.
