### ISSUE TITLE
Code linting not working

### ISSUE THREAD

**Issue by ajitbohra** [attilabuti/vscode-mjml#18]
**My Environment:**

- Windows 10
- Visual Studio Code 1.19.1
- mjml installed globally

**Update:**
Seems like its working partially, attaching the screenshot of markup.

Improper nesting of section is marked but ending tag for body & mjml not marked

![linting](https://user-images.githubusercontent.com/1039236/34365746-db93176e-eab9-11e7-8006-2edf528e0280.JPG)

**Comment by attilabuti** [comment]
Hello @ajitbohra

MJML CLI:
Line 6 (mj-section) — mj-section cannot be used inside mj-column, only inside: mj-container, mj-wrapper

The issue is most likely related to the MJML. Please report the issue here: [https://github.com/mjmlio/mjml/issues](https://github.com/mjmlio/mjml/issues).

**Comment by ajitbohra** [comment]
@attilabuti yes it is appropriate but if you look at line no 11 & 12 linting for the wrong closing tag is not working.

**Comment by attilabuti** [comment]
Please run the following command: `mjml --validate your_file_name.mjml` and after report the issue here: https://github.com/mjmlio/mjml/issues.
