### ISSUE TITLE
VSCode-mjml check error mj-include ????

### ISSUE THREAD

**Issue by KytoSai** [attilabuti/vscode-mjml#19]
My vscode validate mjml check mj-onclude is not support ???

http://prntscr.com/hywz2z

**Comment by attilabuti** [comment]
@KytoSai "Sorry for that, but mjml --validate doesn't support mj-include." [#651](https://github.com/mjmlio/mjml/issues/651) [#4](https://github.com/attilabuti/vscode-mjml/issues/4)
