### ISSUE TITLE
problem with linter and code colors

### ISSUE THREAD

**Issue by vahidm-sp** [attilabuti/vscode-mjml#20]
The really good extension, but 2 problems 

1- linter `<mg-include>` and `<mj-social>` have errors
`<mg-include>`: when I use it inside mg-body or container error occurs while it's not really an error 
`<mj-social>`: when I use custom social networks like my-awesome-network error occurs while its working well in output html 

2- I don't know why but code colors don't appear / it treats my code as plain text

**Comment by attilabuti** [comment]
@vahidm-sp 
Please read the closed issues before opening a new issue.

1 - Linter:
"Sorry for that, but mjml --validate doesn't support mj-include." [#651](https://github.com/mjmlio/mjml/issues/651) [#4](https://github.com/attilabuti/vscode-mjml/issues/4)  [#19](https://github.com/attilabuti/vscode-mjml/issues/19)

2 - Syntax highlight
[mjml-syntax](https://marketplace.visualstudio.com/items?itemName=digitalstreamio.mjml-syntax#overview): VS Code package for the MJML syntax to provide syntax highlight and snippets for your MJML files. [#9](https://github.com/attilabuti/vscode-mjml/issues/9)

[vscode-mjml features](https://github.com/attilabuti/vscode-mjml/blob/master/README.md#features)
