### ISSUE TITLE
Export with different extension

### ISSUE THREAD

**Issue by acespace90** [attilabuti/vscode-mjml#22]
It would be nice if there was the possibility of adding other extensions to the html. For example, export to `namefile.html.hbs`. The markup would always remain html but with an additional extension so that it can also be used within frameworks.

**Comment by attilabuti** [comment]
This will be implemented in the next version.

**Comment by acespace90** [comment]
Great, I can't wait ;)

**Comment by attilabuti** [comment]
Released in v1.1.0
