### ISSUE TITLE
Update Preview with current active document?

### ISSUE THREAD

**Issue by michaelroper** [attilabuti/vscode-mjml#25]
Hi Attila! 

If I have multiple MJML files in my VS Code project, and I switch between them, the preview window will only show the preview for the first document it was opened for. It also won't update to show the preview for subsequent documents, even if I re-run the "Preview to Side" command. The only workaround seems to be closing the preview window, and running the preview command again on the other document.

Is it possible to update the preview window after switching documents to show the current active document, similar to the way the MJML desktop app functions?

Thanks!

**Comment by attilabuti** [comment]
This will be implemented in the next version.

**Comment by michaelroper** [comment]
Awesome, thanks Attila!

**Comment by attilabuti** [comment]
Released in v1.3.0

**Comment by attilabuti** [comment]
Hello @deviant32

First of, what is your operating system and its version? 
Which version of VSCode you are using?
Also which version of the extension are you running?

I have tested this on Windows and Ubuntu, and it worked well.
