### ISSUE TITLE
Linting Error 

### ISSUE THREAD

**Issue by dnuanes** [attilabuti/vscode-mjml#32]
Pertains to latest version: 1.4

Linter is displaying error "Attribute line-height has invalid value: 1.2 for type Unit, only accepts (px, %) units and 1 value(s)" when error does not exist.

Sample occurrence: a line that has commented code i.e.  having error message displayed. Sample occurrence has nothing to do an attribute of line-height.  

When commented code is deleted and following line moved up, error is then displayed for that line, even though following line does not have line-height as an eligible attribute.

`<mjml>
  <mj-head>
    <mj-breakpoint width="600px" />
    <mj-preview></mj-preview>
     (error displayed on this line) 
    <mj-include path="../../components/styles.mjml" />
    
    <mj-include path="../../components/fonts.mjml" />
    <mj-attributes>
      
      <mj-include path="../../components/attributes.mjml" />
    </mj-attributes>
  </mj-head>
  <mj-body>`

**Comment by michaelroper** [comment]
@dnuanes - i was seeing similar behaviour, and figured out that it was related to errors in files that were being referenced by the `mj-include` tags. Eg, an error on line 3 in the included file was showing the linting error on line 3 in the main document, where it didn't make sense.

Not sure what the fix would be though..
