### ISSUE TITLE
classes not rendered

### ISSUE THREAD

**Issue by vcorvid** [attilabuti/vscode-mjml#37]
Are classes expected to work in vscode-mjml?

I've tried adding class definitions to mjml-attributes https://mjml.io/documentation/#mjml-attributes
and also to mjml-style https://mjml.io/documentation/#mjml-style
but I don't see these changes showing up in the VS Code preview or to the html that is output

**Comment by attilabuti** [comment]
Hello @vcorvid

Please try the following:
```xml
<mjml>
  <mj-head>
    <mj-attributes>
      <mj-text padding="0" />
      <mj-class name="blue" color="blue" />
      <mj-class name="big" font-size="40px" />
      <mj-all font-family="Arial" />
    </mj-attributes>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text mj-class="blue big">
          Hello World!
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by vcorvid** [comment]
Yes that works!  The `mj-class=` did it.
I was using `css-class=` as listed in the documentation here https://mjml.io/documentation/#standard-body-components.
Thank you
