### ISSUE TITLE
Preview Pane Background color is not white

### ISSUE THREAD

**Issue by oscaralmaraz** [attilabuti/vscode-mjml#39]
When I activate the preview pane, it has the same background color as the main VS Code.  Is there a way to change this? In all product shots it looks white but  I just installed it and it looks with the same gray background as Code

**Comment by dnuanes** [comment]
Try changing the body background-color for your email. That is likely the issue.

**Comment by ngarnier** [comment]
Yep, that's likely because your email has no background-color (so it's "transparent"). In other products or browsers, the default background is white so transparent on white = white, versus in VSCode the default background is grey so transparent on grey = grey.

**Comment by attilabuti** [comment]
[1.5.0](https://github.com/attilabuti/vscode-mjml/releases/tag/1.5.0) Added ability to set custom background color for the preview pane.
