### ISSUE TITLE
<mj-include> syntax problem

### ISSUE THREAD

**Issue by cbrevik** [attilabuti/vscode-mjml#4]
Awesome extension, thanks so much for you work! 

I'm not sure if it is related to #2, but using `0.0.6` I'm getting the following error using `<mj-include>`:
![image](https://user-images.githubusercontent.com/4932625/27902880-a7b7d26e-6237-11e7-8c09-58a648bbf6eb.png)

It's only a syntax error inside VSCode though, the included file is still rendering inside Preview & exported as HTML.

**Comment by attilabuti** [comment]
@cbrevik "Sorry for that, but `mjml --validate` doesn't support `mj-include`." [#651](https://github.com/mjmlio/mjml/issues/651)

**Comment by cbrevik** [comment]
Aha, I understand. Thanks @attilabuti! :)
