### ISSUE TITLE
Comment with HTML-style comments?

### ISSUE THREAD

**Issue by michaelroper** [attilabuti/vscode-mjml#40]
Hi Attila!

Quick question - when I use the `Command + /` shortcut to comment a line or selection, it is currently only putting `// ` at the start of the line, instead of using HTML comment syntax `<!-- -->`. Is this standard/expected behaviour, or do I possibly have something configured wrong in my VS Code settings?

**Comment by attilabuti** [comment]
Hello @michaelroper

Sorry, this is my fault... I will fix it in the next update.

**Comment by michaelroper** [comment]
Hah, no worries, thanks! :)

**Comment by attilabuti** [comment]
The issue is fixed on 1.5.1.
