### ISSUE TITLE
Beautify document deletes file content

### ISSUE THREAD

**Issue by nik-lampe** [attilabuti/vscode-mjml#42]
Hello,

when I use the MJML: beautify Command on my file the whole file content gets removed.
Haven't had this issue when I used the extension about two months ago.

I'm trying to find some debug output to provide more information, but can't find any.
When I change the language type of the file to html the formatting works just fine.

Any ideas? Maybe some misconfiguration in my settings?

**Comment by attilabuti** [comment]
Hello @nik-lampe,

Can you send me your `mjml.beautify` configuration?

**Comment by nik-lampe** [comment]
Sure, here:

  "mjml.beautify": {
    "indent_size": 2,
    "wrap_attributes_indent_size": 2
  }

@attilabuti

**Comment by attilabuti** [comment]
Hello @nik-lampe

Sorry, this is my fault I will fix it in the next update.

**Comment by lupas** [comment]
Having exactly the same issue. Glad it will be fixed soon. :)

**Comment by gabrielrinaldi** [comment]
Any updates on this @attilabuti? Any workaround while we wait for an update?

**Comment by attilabuti** [comment]
Hello @gabrielrinaldi

I would like to release a new version in this week.

Workaround:
Use `mj-head` in your mjml files.

**Comment by gabrielrinaldi** [comment]
@attilabuti that works! The extension is really great and a huge time saver. Thanks a lot
