### ISSUE TITLE
Block comments not working with MJML files

### ISSUE THREAD

**Issue by sinklair** [attilabuti/vscode-mjml#44]
VS Code doesn't seem to be picking up the right block comments for MJML code. It is applying the default /* */.

**Comment by attilabuti** [comment]
Hello @sinklair

Which `vscode-mjml` version do you use?

**Comment by dnuanes** [comment]
I'm using 1.5.1 and have noticed this too. Initially when I updated to 1.5.1 block comments worked, but have since returned to the /**/ format

**Comment by attilabuti** [comment]
@dnuanes do you have any other extension enabled? Can you try to disable all of them and see if anything changes?

**Comment by dnuanes** [comment]
@attilabuti Good call. For some reason I had another MJML syntax extension installed as well. Once I disabled that, the block comments started working properly.

**Comment by sinklair** [comment]
Ah, good call. Same here. Had another MJML syntax highlighter that was causing the issue.
