### ISSUE TITLE
When exporting MJML to HTML, nav icons generated incomplete HTML decimal code

### ISSUE THREAD

**Issue by dnuanes** [attilabuti/vscode-mjml#49]
Issue appears in version 1.6.0. 

When exporting MJML to HTML that uses navbar, nav icons generated are incomplete HTML decimal code. 

Where the hamburger icon was formerly generated, incomplete HTML decimal is generated: 9776. 

Where the close icon was formerly generated, incomplete HTML decimal is generated: 8855.

**Comment by attilabuti** [comment]
Hello @dnuanes,

Please use the issue template next time and provide all information asked in it.

What is your operating system?
Which version of VSCode you are using?
Can you send me a snippet of code that reproduces the error?

**Comment by dnuanes** [comment]
Hi Attila, 

Sorry, I'll be sure to use the template next time. 

1) Mac OS Sierra
2) VSCode version 1.25
3) `  <div class="mj-menu-trigger" style="display:none;max-height:0px;max-width:0px;font-size:0px;overflow:hidden;">
                        <label for="867916d7619c611f" class="mj-menu-label" style="display:block;cursor:pointer;mso-hide:all;-moz-user-select:none;user-select:none;align:center;color:#ffffff;font-size:30px;font-family:Merriweather, Helvetica;text-transform:uppercase;text-decoration:none;line-height:30px;padding:10px;">
                          <span class="mj-menu-icon-open" style="mso-hide:all;"> 9776 </span>
                          <span class="mj-menu-icon-close" style="display:none;mso-hide:all;"> 8855 </span>
                        </label>
                      </div>`

**Comment by dnuanes** [comment]
Is this sufficient @attilabuti , or would you like more details?
