### ISSUE TITLE
Language mode creates incompatibility with formatting tools

### ISSUE THREAD

**Issue by alexsasharegan** [attilabuti/vscode-mjml#8]
In order for the plugin to register a document as `mjml`, the language mode must match. This doesn't let me tweak the file associations to use built in beautification tools because it needs to recognize `html`. I'm looking to format the source, not the output.

Is there a workaround for this?

**Comment by attilabuti** [comment]
Temporary solution: 
- Open the Command Palette (with Ctrl+Shift+P or F1) > Change Language Mode > HTML
- Open the Command Palette > Format document
- Open the Command Palette > Change Language Mode > MJML

**Comment by attilabuti** [comment]
Released in v0.1.0
