### ISSUE TITLE
No syntax highlighting in VSCode 1.14.2 ?

### ISSUE THREAD

**Issue by martin-gillen** [attilabuti/vscode-mjml#9]
I installed the extension in VSCode 1.14.2.

Lots works...  red squiggly line linting works. 

The screenshot and live preview works.

But there's no syntax highlighting, everything is just plain text.

I disabled all other extensions except this one, didn't help.

**Comment by attilabuti** [comment]
[mjml-syntax](https://marketplace.visualstudio.com/items?itemName=digitalstreamio.mjml-syntax#overview): VS Code package for the MJML syntax to provide syntax highlight and snippets for your MJML files.

[vscode-mjml features](https://github.com/attilabuti/vscode-mjml/blob/master/README.md#features)

**Comment by martin-gillen** [comment]
Thanks!

The videos threw me off, I assumed syntax highlighting was a feature.
